apiVersion: apps/v1
kind: Deployment

metadata:
  name: sre-nginx

spec:
  replicas: 2

  selector:
    matchLabels:
      app: sre-nginx

  template:
    metadata:
      labels:
        app: sre-nginx

    spec:
      imagePullSecrets:
        - name: ghcr-secret

      containers:
        - name: nginx
          image: ghcr.io/charvibarhate/sre-nginx:296698ab55a2bc2721335c35a615699d6a0c0b5f
          ports:
            - containerPort: 80