name: Build, Push and Deploy NGINX

on:
  push:
    branches:
      - phase1

permissions:
  contents: read
  packages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/sre-nginx:${{ github.sha }} .

      - name: Push Docker image
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/sre-nginx:${{ github.sha }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::571841331213:role/GitHubActions-SRE-NGINX
          aws-region: ap-south-1

      - name: Deploy Kubernetes manifest using SSM
        run: |
          # Replace IMAGE_TAG in Git manifest with this commit SHA
          sed "s|IMAGE_TAG|${{ github.sha }}|g" k8s/deployment.yml > deployment-rendered.yml

          # Encode manifest so it can safely travel through SSM
          MANIFEST=$(base64 -w 0 deployment-rendered.yml)

          # Create SSM parameters safely
          jq -n --arg manifest "$MANIFEST" '{
            commands: [
              "echo \($manifest) | base64 -d > /tmp/deployment.yml",
              "sudo kubectl apply -f /tmp/deployment.yml",
              "sudo kubectl rollout status deployment/sre-nginx --timeout=120s",
              "SERVICE_IP=$(sudo kubectl get svc sre-nginx-service -o jsonpath='{.spec.clusterIP}') && curl -fsS http://$SERVICE_IP > /dev/null"S
            ]
          }' > ssm-parameters.json

          COMMAND_ID=$(aws ssm send-command \
            --instance-ids i-0fe6a8a4605c22787 \
            --document-name "AWS-RunShellScript" \
            --parameters file://ssm-parameters.json \
            --region ap-south-1 \
            --query "Command.CommandId" \
            --output text)

          echo "SSM Command ID: $COMMAND_ID"

          aws ssm wait command-executed \
            --command-id "$COMMAND_ID" \
            --instance-id i-0fe6a8a4605c22787 \
            --region ap-south-1